name: snapshotter test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
      - "[0-9]+.[0-9]+"
    tags:
      - "v*"
  pull_request:

jobs:
  test:
    if: contains(github.event.pull_request.labels.*.name, 'containerd-integration')
    uses: ./.github/workflows/.test.yml
    with:
      use_snapshotter: true
      graph_driver: overlayfs
